import type { NextPage } from 'next'
import Head from 'next/head'
// import { Button } from "@/components/layouts/Header;



//review
const Home: NextPage = () => {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
      トップページ
      </main>
    </div>
  )
}
// classNameはtailwindで記述 

export default Home
