import type { NextPage } from 'next'
import Head from 'next/head'


//review
const Home: NextPage = () => {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-red-700 text-white inline-block p-10 rounded-lg font-bold'>学習管理アプリ</main>
    </div>
  )
}
// classNameはtailwindで記述 

export default Home
